version: '3.9'

services:
  nginx:
    image: oreplay/backend-python:0.0.1a8
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - .:/app/
    env_file:
      - .env.example
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - oreplay_backend_oreplay_network

networks:
  oreplay_backend_oreplay_network:
    external: true