name: Run Tests and Upload to SonarCloud

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  sonarcloud:
    name: Run Tests, Generate Coverage, and Upload to SonarCloud
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Choose the Python version that matches your project

      # Install pipenv
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      # Install dependencies using pipenv
      - name: Install dependencies with Pipenv
        run: |
          pipenv install --dev  # This installs both default and development dependencies

      # Run tests and generate coverage report using pipenv and pytest
      - name: Run tests with coverage
        run: |
          pipenv run coverage run -m pytest  # Run tests with coverage tracking
          pipenv run coverage report  # Show coverage in the console
          pipenv run coverage xml -o coverage.xml  # Generate the coverage report in XML format
